# Generated by Django 3.2.2 on 2021-08-09 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('uname', models.CharField(max_length=34)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=20)),
                ('address1', models.CharField(blank=True, default=None, max_length=30)),
                ('address2', models.CharField(blank=True, default=None, max_length=30)),
                ('city', models.CharField(blank=True, default=None, max_length=30)),
                ('state', models.CharField(blank=True, default=None, max_length=30)),
                ('pin', models.CharField(blank=True, default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('uname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.CharField(blank=True, default=None, max_length=50)),
                ('bankname', models.CharField(blank=True, default=None, max_length=50)),
                ('ifsccode', models.CharField(blank=True, default=None, max_length=20)),
                ('accountnumber', models.CharField(blank=True, default=None, max_length=25)),
                ('total', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('baseprice', models.IntegerField()),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('finalprice', models.FloatField(blank=True, default=0, null=True)),
                ('red', models.BooleanField(blank=True, default=False, null=True)),
                ('green', models.BooleanField(blank=True, default=False, null=True)),
                ('white', models.BooleanField(blank=True, default=False, null=True)),
                ('pink', models.BooleanField(blank=True, default=False, null=True)),
                ('xs', models.BooleanField(blank=True, default=False, null=True)),
                ('s', models.BooleanField(blank=True, default=False, null=True)),
                ('m', models.BooleanField(blank=True, default=False, null=True)),
                ('l', models.BooleanField(blank=True, default=False, null=True)),
                ('xl', models.BooleanField(blank=True, default=False, null=True)),
                ('xxl', models.BooleanField(blank=True, default=False, null=True)),
                ('img1', models.ImageField(blank=True, default=None, upload_to='images/')),
                ('img2', models.ImageField(blank=True, default=None, upload_to='images/')),
                ('img3', models.ImageField(blank=True, default=None, upload_to='images/')),
                ('img4', models.ImageField(blank=True, default=None, upload_to='images/')),
                ('img5', models.ImageField(blank=True, default=None, upload_to='images/')),
                ('date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.seller')),
            ],
        ),
    ]
